### ISSUE TITLE
Proponer incluir en la documentación: Un método alterno del response_format  en los lineamientos del OAS - 1 horas - Miguel y Felipe

### ISSUE THREAD

**Issue by miguelramirez93** [udistrital/utils_oas#7]
- [x] Generar documentación para response format en utils_oas

**Comment by Soulfilip-UD** [comment]
Próxima reunión para socialización con los arquitectos el Martes 9 de Julio a las 11am

**Comment by Soulfilip-UD** [comment]
Documentación realizada, Reunión realizada, la finalización de la tarea está completa. Para la integración en los lineamientos del OAS, debe someterse a unas pruebas que hacen parte del siguiente [Issue](https://github.com/udistrital/introduccion_oas/issues/2).
Proceeding to close Issue :space_invader:
